# -------- Build --------
FROM ubuntu:latest AS builder

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
        bash \
        clang \
        clang-tools \
        build-essential \
        cmake \
        ninja-build \
        pkg-config \
        libtool \
        autoconf \
        automake \
        tar \
        curl \
        ca-certificates \
        libpq-dev \
        libcjson-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp

RUN update-ca-certificates && \
    curl -fsSL https://ftp.gnu.org/gnu/libmicrohttpd/libmicrohttpd-1.0.2.tar.gz -o libmicrohttpd.tar.gz && \
    tar xf libmicrohttpd.tar.gz && \
    cd libmicrohttpd-1.0.2 && \
    ./configure --disable-https && \
    make -j"$(nproc)" && \
    make install

WORKDIR /app

COPY CMakeLists.txt .
COPY src/ src/

ENV CC=clang

RUN cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release . && \
    cmake --build build

# -------- Run --------
FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
        libpq5 \
        libcjson1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /usr/local/lib/libmicrohttpd.so* /usr/local/lib/
COPY --from=builder /app/build/src/pg-status /app/pg-status

ENTRYPOINT ["/app/pg-status"]
