# -------- Build --------
FROM ubuntu:latest AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    clang \
    clang-tools \
    build-essential \
    cmake \
    ninja-build \
    pkg-config \
    libpq-dev \
    libmicrohttpd-dev \
    libcjson-dev && \
    rm -rf /var/lib/apt/lists/*

ENV CC=clang
WORKDIR /app

COPY CMakeLists.txt .
COPY src/ src/

RUN cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release . && \
    cmake --build build

# -------- Export --------
FROM scratch AS export
COPY --from=builder /app/build/src/pg-status /pg-status

# -------- Run --------
FROM ubuntu:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq5 \
    libmicrohttpd12 \
    libcjson1 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/build/src/pg-status /app/pg-status

ENTRYPOINT ["/app/pg-status"]
