# -------- Build --------
FROM ubuntu:24.04 AS builder

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    clang \
    clang-tools \
    build-essential \
    cmake \
    ninja-build \
    pkg-config \
    libpq-dev \
    libevent-dev \
    libcjson-dev && \
    rm -rf /var/lib/apt/lists/*

ENV CC=clang
WORKDIR /app

COPY CMakeLists.txt .
COPY src/ src/
COPY test/CMakeLists.txt test/
COPY test/tests/ test/tests/

RUN cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release . && \
    cmake --build build && \
    ctest --test-dir build --output-on-failure

# -------- Package Archive --------
FROM ubuntu:24.04 AS packager

WORKDIR /archive

COPY --from=builder /app/build/src/pg-status pg-status
COPY LICENSE LICENSE
COPY docker/ubuntu/package/shared-third-party-notices.txt THIRD-PARTY-NOTICES
COPY docker/ubuntu/package/shared-readme.txt README

# Создаём архив
RUN apt-get update && apt-get install -y --no-install-recommends tar gzip && \
    rm -rf /var/lib/apt/lists/*

RUN architecture="$(dpkg --print-architecture)" && \
    tar -czvf "/pg-status_2.2.0_linux_${architecture}_shared.tar.gz" \
        pg-status \
        LICENSE \
        THIRD-PARTY-NOTICES \
        README

# -------- Export --------
FROM scratch AS export
COPY --from=packager /pg-status_2.2.0_linux_*_shared.tar.gz /

# -------- Run --------
FROM ubuntu:24.04 AS runtime

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    libpq5 \
    libevent-2.1-7t64 \
    libcjson1 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/build/src/pg-status /app/pg-status

ENTRYPOINT ["/app/pg-status"]
