# -------- Build --------
FROM ubuntu:24.04 AS builder

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    clang \
    clang-tools \
    build-essential \
    cmake \
    ninja-build \
    pkg-config \
    libpq-dev \
    libevent-dev \
    libcjson-dev && \
    rm -rf /var/lib/apt/lists/*

ENV CC=clang
WORKDIR /app

COPY CMakeLists.txt .
COPY src/ src/
COPY test/CMakeLists.txt test/
COPY test/tests/ test/tests/

RUN cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release . && \
    cmake --build build && \
    ctest --test-dir build --output-on-failure

# -------- Deb Package --------
FROM ubuntu:24.04 AS packager

WORKDIR /pkgroot

RUN mkdir -p DEBIAN usr/bin usr/share/doc/pg-status

COPY --from=builder /app/build/src/pg-status usr/bin/pg-status
COPY docker/ubuntu/package/debian-control DEBIAN/control
COPY docker/ubuntu/package/debian-copyright usr/share/doc/pg-status/copyright

RUN architecture="$(dpkg --print-architecture)" && \
    sed -i "s/PACKAGE_ARCHITECTURE/${architecture}/" DEBIAN/control

RUN chmod 755 usr/bin/pg-status && chmod 755 DEBIAN

RUN architecture="$(dpkg --print-architecture)" && \
    dpkg-deb --build . "/pg-status_2.2.0_${architecture}.deb"

# -------- Export --------
FROM scratch AS export
COPY --from=packager /pg-status_2.2.0_*.deb /
