# -------- Build --------
FROM alpine:3.22 AS builder

RUN apk add --no-cache \
        clang \
        clang-extra-tools \
        build-base \
        bsd-compat-headers \
        cmake \
        ninja \
        pkgconfig \
        libpq-dev \
        libevent-dev \
        cjson-dev

ENV CC=clang

WORKDIR /app

COPY CMakeLists.txt .
COPY src/ src/
COPY test/CMakeLists.txt test/
COPY test/tests/ test/tests/

RUN cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release . && \
    cmake --build build && \
    ctest --test-dir build --output-on-failure

# -------- Export --------
FROM scratch AS export
COPY --from=builder /app/build/src/pg-status /pg-status


# -------- Run --------
FROM alpine:3.22

RUN apk add --no-cache \
        libpq \
        libevent \
        cjson

WORKDIR /app

COPY --from=builder /app/build/src/pg-status /app/pg-status

ENTRYPOINT ["/app/pg-status"]
